---
abstract: 'Graphviz Perl interface with DSL'
author:
  - 'Syohei YOSHIDA <syohex@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Graphviz-DSL
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  File::Which: 0
  parent: 0
  perl: 5.8.1
resources:
  license: http://dev.perl.org/licenses/
  repository: git://github.com/syohex/p5-Graphviz-DSL.git
version: 0.02
